### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by riemers** [OpenFactorioServerManager/factorio-server-manager#122]
Initial setup didn't tell me in the readme that i had to use admin/factorio. 

Upon starting the server it tried to find save games in the /opt/factorio-server-manager directory. I believe that is wrong since the gui looks for files in /opt/factorio/saves. 

I manually created a save and moved it to /opt/factorio/saves and then i was able to start a server.

I did see a big PR so it might be in there too, but from scratch this is what i encountered.

**Comment by mroote** [comment]
Did you launch the docker container with all the volumes mapped to your filesystem?

**Comment by riemers** [comment]
Yes i did

**Comment by riemers** [comment]
Also if i restart the container, it recreates the default admin/factorio username/password. Don't think it is persistant then.

/opt/factorio-server-manager/auth.leveldb is where it creates my new user, but there was no mention that i needed to map this as a volume.

**Comment by knoxfighter** [comment]
All of that is fixed with the new UI. With the new docker files the leveldb/sqlitedb are defined as volume by default. (Cause they are inside `/opt/fsm-data/`
