### ISSUE TITLE
Gameconfig setting (non_blocking_saving) always false

### ISSUE THREAD

**Issue by Scaramuz** [OpenFactorioServerManager/factorio-server-manager#129]
Hi,

i can change every gamesetting in the server-settings.json file via the factorio-server-manager, except "non_blocking_saving" it always changes to false after server start or updating the setting.
Im using Ubuntu 18.04 server

**Comment by knoxfighter** [comment]
I can confirm this bug. It is not only not saved, but also not correctly read.
It the frontend is always printed as True, even if its false in the config file.
Also when starting factorio it is automatically turned to false by the factorio server.

**Comment by knoxfighter** [comment]
Fixed with #186. Will be added to the next release.

**Comment by jelutz77** [comment]
This is apparently an issue again
