### ISSUE TITLE
Server is not responding Message Every 30secs

### ISSUE THREAD

**Issue by hanwellr** [OpenFactorioServerManager/factorio-server-manager#130]
I'm running the docker VM in FreeNAS with the Factorio Container server manager. Not issue all works fine. 

When I host the game it shows in the server list with ping at 1ms. 

However once in the game environment. I get ervery 30sec the Server is not responding popup message. 

I've check the CPU in the docker VM and Memory no issue. Network IO not sure how to check this. 

Factorio logs shows a fragment warning every so often. 

How can i check the network IO and is the factorio-server-manager running anything over the network creating the issue. 

I've tested Factrio server on FreeNAS as a Linux VM no issues.

**Comment by mroote** [comment]
Hi @hanwellr, is this still an issue for you? I suspect the issue is something to due with resources on your server. If you have the log message with the fragment warning that might be helpful.
