### ISSUE TITLE
FSM doesn't detect when factorio binary is updated

### ISSUE THREAD

**Issue by dgw** [OpenFactorioServerManager/factorio-server-manager#147]
I'm sure this will be fixed if/when #10 is implemented (at the latest), but I think it's worthy of a separate issue anyway.

At present, after updating the Factorio binary using an external tool (in my case, [narc0tiq/factorio-updater](https://github.com/narc0tiq/factorio-updater)), FSM may show an updated mod (in my case, [Even Distribution 0.3.7](https://github.com/321freddy/even-distribution/compare/0b66ccb...f9456ac)) as incompatible because it's checking `base` dependencies against the Factorio version that was installed _when FSM was started_ instead of the version that is _currently_ installed.

Restarting FSM made the false "not compatible" flag go away, so I presume FSM is caching the installed Factorio binary version somewhere and not updating it as often as expected (if at all).

Between starting FSM and tonight, I upgraded Factorio about 4-5 times, which is why FSM thought I had a version below 0.17.35 installed. (Apparently FSM also doesn't re-cache the installed version number when starting/stopping the Factorio server, because the last start and stop operations before I restarted FSM were performed with Factorio 0.17.35.)

----

Note: My upgrade process for Factorio is as follows:

- Stop Factorio through FSM
- Run shell command `python3 /path/to/factorio-updater/update_factorio.py -Dxa /path/to/factorio/binary` to upgrade that specific `binary` to the latest experimental version
- Check FSM's mods page and update all, if any updates are available
- Start Factorio through FSM

**Comment by knoxfighter** [comment]
The Server Manager cant detect, when the factorio executable is changed. It is designed to manage one installation and this installation is not allowed to be changed by external programs. So your update process should be like:
- Stop Factorio through FSM
- Stop FSM
- Run shell command python3 /path/to/factorio-updater/update_factorio.py -Dxa /path/to/factorio/binary to upgrade that specific binary to the latest experimental version
- Start FSM
- Check FSM's mods page and update all, if any updates are available
- Start Factorio through FSM

And i dont know, if #10 will ever be implemented. The thing is, the complete FSM has to be rewritten with a different goal in mind. I am currently thinking about making a FSMv2, where it also should also be possible to manage multiple factorio servers. This would be a complete rewrite and would take a long time to implement :(

**Comment by dgw** [comment]
I think it would be a lot simpler than a full v2 rewrite to check the `factorio` binary version periodically during operations. If this issue languishes for long enough, I just might find the time to learn enough Go to try addressing it myself.

**Comment by Psychomantis71** [comment]
@dgw as @knoxfighter said, you only need to stop the FSM too while updating your factorio binary, after the update just start it again. The only solution I see to this problem would be to have a built in way to update the factorio binary (as you mentioned #10 ), but even then, with the current code FSM would have to restart in order to pick up the new version.

**Comment by knoxfighter** [comment]
With the new Dockerfiles, it is also possible, to just restart the docker container to update factorio. An update feature, from the UI is also planned in the futute:tm:.
