### ISSUE TITLE
What is the future of Factorio Server Manager?

### ISSUE THREAD

**Issue by jannaahs** [OpenFactorioServerManager/factorio-server-manager#175]
Dear @mroote ,
thank you for this awesome project. It is very useful to manage my factorio server.

After using FSM for a while, I would like to contribute and started to rework the UI.
Now I noticed the project hasn't been updated in the last 6 months.

Are there any future plans for FSM?

I believe there are some good ideas how to improve FSM like #10.

Cheers,
Jan

**Comment by knoxfighter** [comment]
I dont think mroote has much of a plan about the future of this project and i dont had the time and motivation yet to think abut a v2 of this project (a server manager, that is not handling a single server, but multiple instances with user managemant and what not).
One thing i wanted to do for a while know is creating a button to update factorio autmatically (but ... time ...). What are your plans for the UI rework (im happy with the admin-lte look of it)?

Also every contribution is appreciated and im here to check and merge PRs :)

**Comment by mroote** [comment]
HI Jan,

Thanks I'm glad you like the project. I haven't been as active lately with FSM, other projects and time have gotten in the way unfortunately. I'd be happy to accept any improvements and contributions if you are looking at adding features or improving them.  https://github.com/mroote/factorio-server-manager/issues/10 would be a great feature to add for sure if you are looking to tackle that one.

**Comment by jannaahs** [comment]
Here is a screenshot of my work in progress. I started from scratch and there is still a lot to do.

![grafik](https://user-images.githubusercontent.com/5788643/89124648-ed734380-d4d8-11ea-85d3-782b2abf19c1.png)

I would like to improve the UI before adding new features. Otherwise I have to integrate the new features in both designs.
Currently I am working on the mods page.

PS: I am playing a lot of factorio 😉.

**Comment by mroote** [comment]
Nice! that looks great.

**Comment by knoxfighter** [comment]
ok, that is an awesome design idea! It would be a great idea to have the manager also look like factorio.
If you finished all designs, we could work together to implement it faster :)

**Comment by jannaahs** [comment]
@knoxfighter yeah that sounds great!
The design is already finished. It will require some polishing, which I will do during the implementaion.

How do you think we should proceed?

**Comment by knoxfighter** [comment]
I would say, we should talk with each other (discord or so) and discuss the design (to fix flaws) and how we would like to implement it (css-framwork, backend changes, etc.).

**Comment by jannaahs** [comment]
@knoxfighter sounds good. I have sent you an email.

**Comment by Psychomantis71** [comment]
@jannaahs @knoxfighter that does seem interesting to me too, would you mind including me in those talks too?

**Comment by jannaahs** [comment]
@Psychomantis71 how can we contact you?

**Comment by Psychomantis71** [comment]
@jannaahs contact me via mail or discord (PsychoMantis#8879 on discord) :)

**Comment by Hiekie** [comment]
I am very! interested in the server manager! Sadly i can not program at all, but i would love to contribute to it by testing it.
Running a factorio - server on Unbuntu 16.04 and would love to run more then one instance.
I use this Factorio Server to contribute to such called LANparty - events, to let people have fun playing their game and hosting it on my VM platform (some big servers all running the XCP-NG VM Hypervisor.)

**Comment by jannaahs** [comment]
@mroote @knoxfighter 

I want to give an update on my progress so far.

I implemented all functionallities beside the Mods and ModPacks.
There is also some final work to do like updating the changelog, the readme and clean up the dependencies.

Additionally I have added a Help Section which looks like this:

![grafik](https://user-images.githubusercontent.com/5788643/91542132-a7fe3680-e91d-11ea-8d2c-363dca9f9c69.png)


Do you have any suggestion what can be added here?
