### ISSUE TITLE
Rename Project?

### ISSUE THREAD

**Issue by jannaahs** [OpenFactorioServerManager/factorio-server-manager#182]
Based on the design I posted in #175 I have ask Wube Software for permission to use the background image and the gear from the factorio logo. They don't allow us to use any of the graphics.

Additionally they proposed to rename the project from "Factorio Server Manager" to "Open Factorio Server Manager", because the current name sounds too offical and they would like to avoid the situation where people will think it is an official Factorio project.

@mroote how do you want to proceed?

I think the project should be renamed to avoid trouble.

**Comment by mroote** [comment]
I'm fine with adding open to the name. I'm not sure if we have confusing people with this project and the official Wube ones but I'm fine with changing the name if there is some concern about the naming causing confusion.

**Comment by jannaahs** [comment]
@knoxfighter Will the repository be renamed as well?

**Comment by knoxfighter** [comment]
Project renamed to `Open Factorio Server Manager`
