### ISSUE TITLE
Factorio not updating to 1.0

### ISSUE THREAD

**Issue by maxcerny** [OpenFactorioServerManager/factorio-server-manager#183]
The server manager doesn't install with factorio 1.0

**Comment by knoxfighter** [comment]
It will use, the version you say it, it should use (with the parameter `--dir`).
If you are using the docker container, it should automatically use `latest` and that is 1.0.0.
An automatic update is currently not possible, so you need to recreate the docker-container or update your factorio server files manually.

**Comment by maxcerny** [comment]
I am recreating the container but it is defaulting to 0.18.something

**Comment by knoxfighter** [comment]
oh, yes, its the container on docker-hub, that has an older version in it, so you need to rebuild the docker-container yourself. Just clone the project, go into the docker directory and execute `build.sh` and then it should create a newer container automatically.

**Comment by maxcerny** [comment]
that will be kinda tricky to do since I am running it in unraid ui. isn't there some sort of env variable that i can use to modify this?

**Comment by knoxfighter** [comment]
unluckily no :(

**Comment by maxcerny** [comment]
and any chance of the docker it self being updated?

**Comment by knoxfighter** [comment]
@mroote Can you please update the docker image on the docker-hub, to the newest factorio version?

Also we will work on an update feature (from the UI) in the near future ;)

**Comment by maxcerny** [comment]
Thanks.
Also is there any way I could help expedite the process? (ui update, not the docker)

**Comment by knoxfighter** [comment]
We're current working on a completely new UI (#175 ) after that we will work on some fixes and the Server Update from our UI.

**Comment by maxcerny** [comment]
How soon can I expect the dockerfile to be updated?

**Comment by maxcerny** [comment]
Even after the update, I'm still getting this error
12.994 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "Map version 1.0.0-0 cannot be loaded because it is higher than the game version (0.18.46-0)."

**Comment by maxcerny** [comment]
nevermind, my docker pull is still pulling the old img for some reason

**Comment by knoxfighter** [comment]
The newest version is still with factorio 0.18.46.0
@mroote you need to rebuild the docker image completely, to have a newer factorio version inside.

**Comment by maxcerny** [comment]
but i am still getting the image that was made 3 weeks ago

**Comment by knoxfighter** [comment]
oh, you're right. I would say, he created it 3 weeks ago and just uploaded it today.

**Comment by maxcerny** [comment]
might be

**Comment by maxcerny** [comment]
Any updates?

**Comment by jesta030** [comment]
i'm trying to run the docker hub image on UnRAID but it's still not on 1.0.0:

docker run -d --name='FactorioManager' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -p '8082:80/tcp' -p '8445:443/tcp' -p '34197:34197/udp' -v '/mnt/user/appdata/factorio-manager/config':'/opt/factorio/config':'rw' -v '/mnt/user/appdata/factorio-manager/saves':'/opt/factorio/saves':'rw' -v '/mnt/user/appdata/factorio-manager/mods':'/opt/factorio/mods':'rw' 'majormjr/factorio-server-manager' 

What's the way to get this to 1.0.0?

**Comment by jesta030** [comment]
@maxcerny 

I built and pushed a docker image with 1.0.0 at https://hub.docker.com/r/jesta030/factorio-server-manager
Working on UnRAID except for the server log, that seems to be broken currently but can be viewed from the container's console ( /opt/factorio/factorio-server-console.log)

**Comment by knoxfighter** [comment]
Currently the factorio version that is inside the docker image will stay in the docker image, it had no way to update the version, without rebuilding the image.
Currently we have a PR #185 that includes an easily updateable docker image. It is also already uploaded to the dockerhub too.

[Readme](https://github.com/ita-sammann/factorio-server-manager/tree/new-docker-bundle/docker)
[Image on dockerhub](https://hub.docker.com/r/sammann/fsm-docker)
