### ISSUE TITLE
Difference in ofsm image reference

### ISSUE THREAD

**Issue by xlSilentHublx** [OpenFactorioServerManager/factorio-server-manager#190]
In development branch...

docker-compose.simple.yaml references image: "ofsm/ofsm:**latest**"
docker-compose.yaml references image: "ofsm/ofsm:**develop**"

**Comment by knoxfighter** [comment]
Both use `develop` for now, when we create the next release, we will change it to `latest`

**Comment by knoxfighter** [comment]
Both are updated to `latest` now.
