### ISSUE TITLE
Docker Installation issues

### ISSUE THREAD

**Issue by dzzhyk** [OpenFactorioServerManager/factorio-server-manager#192]
Hi guys,
I am trying to deploy this project with Docker, but after running the image, I cannot enter the management dashboard through localhost:8080.
I tried opening port 8080 in Docker's run command, and it worked.
Perhaps this command should be added to README.md, too.

```shell
docker run --name factorio-manager -d -p 80:80 -p 443:443 -p 8080:8080 -p 34197:34197/udp majormjr/factorio-server-manager
```

**Comment by knoxfighter** [comment]
The readme is outdated currently, yes, the server is binding itself by default to port 8080. This for sure is a bug :)

**Comment by knoxfighter** [comment]
By default the port, that is listened to, is 80 again.
