### ISSUE TITLE
 Port number not changing when running two factorio servers in separate docker containers

### ISSUE THREAD

**Issue by xlSilentHublx** [OpenFactorioServerManager/factorio-server-manager#193]
increment/decrement port not changing port when running two instances in separate docker containers.  I am trying to run factorio server on ports 34197 & 34198 but the GUI does not allow you to set the server port manually as it appears to be hard coded with functions to change the port if another Factorio server instance is detected.

This is a problem when trying to host multiplayer games where people connect from "Browse Public Multiplayer Games" menu in Factorio as the advertised port is wrong. Need to advertise the publicly exposed port not the Factorio server port inside the container.

Note: All config files have been changed to reference ports 81 & 34198 but gui still starts the game on port 34197.  This port seems to be hard coded in ServerCtl.jsx.

_docker ps _output__
COMMAND                           PORTS                                                     NAMES
 "/opt/entrypoint.sh"  **34197/udp, 0.0.0.0:34198->34198/udp, 0.0.0.0:81->80/tcp**   factorio-server-manager-2
"/opt/entrypoint.sh"   0.0.0.0:80->80/tcp, 0.0.0.0:34197->34197/udp              factorio-server-manager

**Comment by knoxfighter** [comment]
interesting. Just one thing, why even change the port in the web interface, when your already in a docker container? Just map the port to a different port on the host:
`docker run --name factorio-manager -d -p 81:80 -p 34198:34197/udp sammann/fsm-docker:latest

**Comment by xlSilentHublx** [comment]
I updated my post with a explanation as to why its an issue.

**Comment by xlSilentHublx** [comment]
How can I run the updated gui?

**Comment by knoxfighter** [comment]
>How can I run the updated gui?
That is not yet possible. As soon as it is merged into the develop branch it is available as a docker container `ofsm/ofsm:develop`

**Comment by knoxfighter** [comment]
The updated UI is now available with the docker container `ofsm/ofsm:develop`.
Some more fixes and changes will be added, before we create a new release :)

**Comment by knoxfighter** [comment]
This should not be a problem anymore, New UI can be used with `ofsm/ofsm:latest` now. If this error still persists, please reopen the issue or create a new one.
