### ISSUE TITLE
Lonely c in the Layout.jsx file

### ISSUE THREAD

**Issue by cheetahx7x** [OpenFactorioServerManager/factorio-server-manager#196]
In the Layout.jsx file is a lonely c which gets added onto the ui.
![image](https://user-images.githubusercontent.com/32615204/101653353-8560db00-3a3f-11eb-812c-10f50eeccc50.png)
![image](https://user-images.githubusercontent.com/32615204/101653243-682c0c80-3a3f-11eb-9638-53a9ffd2b3cc.png)

**Comment by mroote** [comment]
Thanks! didn't c that one.

**Comment by mroote** [comment]
Fixed in https://github.com/OpenFactorioServerManager/factorio-server-manager/commit/2c62426212672e852cd1e56b7d857224528a3089
