### ISSUE TITLE
Not prompted to update mods when there is a new version (Develop Branch)

### ISSUE THREAD

**Issue by samgray96** [OpenFactorioServerManager/factorio-server-manager#208]
Sorry, found another issue with the Mods page, mod has been updated in the mod portal but isn't showing there is an update available not sure if this is intentional but as the previous (UI) version does prompt about updates I assume this is a bug, screenshots attached and I can grab the log if that helps

Thanks

<img width="953" alt="Screenshot 2020-12-30 at 18 22 01" src="https://user-images.githubusercontent.com/4542810/103373281-68fb1000-4acc-11eb-9838-aa15f98f3adc.png">
<img width="489" alt="Screenshot 2020-12-30 at 18 22 15" src="https://user-images.githubusercontent.com/4542810/103373286-6c8e9700-4acc-11eb-94fa-e130d0324829.png">

**Comment by knoxfighter** [comment]
Nothing to be sorry about, that is a bug and bugs need to be reported to be resolved. Just tell me the mod, that is causing it (it is not obvious based on the screenshots).

**Comment by samgray96** [comment]
Oh sorry, it's Industrial Revolution 2 that was updated

**Comment by knoxfighter** [comment]
That was a general problem with the calculation of the compatibility to factorio. The update button is available again :smile:
