### ISSUE TITLE
Rebuild Authentication

### ISSUE THREAD

**Issue by jannaahs** [OpenFactorioServerManager/factorio-server-manager#216]
The used library was last updated 5 years ago and is not developed anymore.
 
Also middlewares can be used.

**Comment by knoxfighter** [comment]
- [x] Login
- [ ] Redirect after login
- [x] Logout
- [ ] Add user
- [ ] Remove user
- [ ] Change password
- [ ] Error messaging (All errors are just moved, but nothing is printed (backendside))
- [ ] fix ws connection error 500
