### ISSUE TITLE
[save].tmp.zip bad zip file (Win10)

### ISSUE THREAD

**Issue by nielrio** [OpenFactorioServerManager/factorio-server-manager#225]
Every time I 'Save & Stop Server' (on windows 10) it starts saving, This happens:

2021/01/17 21:49:00 Sent SIGINT to Factorio process. Factorio shutting down...
2021/01/17 21:49:00 Factorio Server:   32.432 Received SIGINT, shutting down
2021/01/17 21:49:00 Factorio Server:   32.448 Quitting: signal.
2021/01/17 21:49:00 Factorio Server:   32.448 Info MainLoop.cpp:417: Saving map as C:\Users\nielrio\Desktop\Servers\Factorio\factorio-server-manager\saves\Save_file.zip
2021/01/17 21:49:01 Factorio Server:   32.972 Info MainLoop.cpp:428: Saving progress: 0.003539%
2021/01/17 21:49:02 Factorio Server:   33.972 Info MainLoop.cpp:428: Saving progress: 97.111908%
2021/01/17 21:49:02 Factorio Server:   33.998 Info MainLoop.cpp:428: Saving progress: 100.000000%
2021/01/17 21:49:02 new state, will also send to correct room
2021/01/17 21:49:02 Factorio server stopped
2021/01/17 21:49:02 Factorio process exited with error: exit status 1
2021/01/17 21:49:02 Error starting Factorio server: exit status 1

Looks like when the factorio server is saving, it creates a .tmp.zip file, but it doesen't get the time to copy to .zip

Do more people have this issue?

**Comment by nielrio** [comment]
When I do --start-server-load-latest the next time, the server quits with 'Bad zip file'

Explorer.exe also says 'Bad zip file'

**Comment by knoxfighter** [comment]
Cannot confirm on ubuntu 18.04. .tmp.zip file will be renamed after write is done. I will test it on Windows later. This could also just be a problem with factorio itself.

**Comment by knoxfighter** [comment]
Cannot confirm on Windows 7. Please send me the files (the working save and the .tmp.zip file) so i can have a deeper look, what's goind on. @nielrio

**Comment by nielrio** [comment]
[Island revived.zip](https://github.com/OpenFactorioServerManager/factorio-server-manager/files/5868699/Island.revived.zip)
[Island revived.tmp.zip](https://github.com/OpenFactorioServerManager/factorio-server-manager/files/5868704/Island.revived.tmp.zip)

Btw, I am not able to recreate the .tmp.zip anymore.

so I guess it's working fine now.

Factorio still exits with error status 1 tho, or is that normal?

**Comment by knoxfighter** [comment]
I got it myself once now. It seems like the .tmp.zip file is just a file, that remains by accident. The normal .zip mp seems to be the successfully saved map, that just can be used to start. I think we should just hide .tmp.zip files.

**Comment by nielrio** [comment]
Ok, then I will close this with this comment, and the .tmp.zip hiding is a good one.

Tnx for support!
