### ISSUE TITLE
Error starting factorio, when no save is present

### ISSUE THREAD

**Issue by Omaha2002** [OpenFactorioServerManager/factorio-server-manager#232]
I installed the docker version with https/letsencrypt (https://hub.docker.com/r/ofsm/ofsm) , interface coming up nicely with certificate in the browser:

![image](https://user-images.githubusercontent.com/3179748/105331956-59a34a00-5bd4-11eb-903e-9f19d7f2fac1.png)

although when I want to start a server, the log shows:

0.000 2021-01-21 10:07:45; Factorio 1.1.12 (build 57713, linux64, headless)
0.000 Operating system: Linux
0.000 Program arguments: "/opt/factorio/bin/x64/factorio" "--bind" "0.0.0.0" "--port" "34197" "--server-settings" "/opt/factorio/config/server-settings.json" "--rcon-port" "43887" "--rcon-password" <private> "--server-adminlist" "/opt/factorio/config/server-adminlist.json" "--start-server-load-latest"
0.000 Read data path: /opt/factorio/data
0.000 Write data path: /opt/factorio [13261/20030MB]
0.000 Binaries path: /opt/factorio/bin
0.005 System info: [CPU: Common KVM processor, 2 cores, RAM: 1987 MB]
0.005 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
0.005 Running in headless mode
0.008 Loading mod core 0.0.0 (data.lua)
0.057 Loading mod base 1.1.12 (data.lua)
0.314 Loading mod base 1.1.12 (data-updates.lua)
0.441 Checksum for core: 2754873018
0.441 Checksum of base: 1000795258
0.612 Prototype list checksum: 2590252455
0.654 Info PlayerData.cpp:70: Local player-data.json available, timestamp 1611223664
0.654 Info PlayerData.cpp:77: Cloud player-data.json unavailable
0.657 Factorio initialised
0.657 Info ServerSynchronizer.cpp:29: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
0.657 Info ServerMultiplayerManager.cpp:780: updateTick(4294967295) changing state from(Ready) to(PreparedToHostGame)
0.657 Info ServerMultiplayerManager.cpp:780: updateTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame)
0.658 Loading map /opt/fsm/
0.675 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "level.dat not found."
0.676 Info ServerMultiplayerManager.cpp:780: updateTick(4294967295) changing state from(CreatingGame) to(InitializationFailed)
0.676 Info CommandLineMultiplayer.cpp:209: Exit point.
0.679 Info ServerMultiplayerManager.cpp:140: Quitting multiplayer connection.
0.679 Info ServerMultiplayerManager.cpp:780: updateTick(4294967295) changing state from(InitializationFailed) to(Closed)
0.705 Info UDPSocket.cpp:218: Closing socket
0.706 Goodbye
apparently it can't find /opt/fsm/level.dat   

docker exec -it factorio-server-manager ls -la /opt/fsm/
total 13656
drwxr-xr-x    1 root     root          4096 Jan 21 07:10 .
drwxr-xr-x    1 root     root          4096 Jan 21 07:02 ..
drwxr-xr-x    2 root     root          4096 Jan  7 16:33 app
-rw-r--r--    1 root     root           264 Jan  7 16:33 conf.json
-rwxr-xr-x    1 root     root      13952002 Jan  7 16:33 factorio-server-manager
-rw-r--r--    1 root     root            67 Jan 21 07:10 factorio.auth
drwxr-xr-x    2 root     root          4096 Jan 21 07:02 mod_packs

**Comment by mroote** [comment]
It looks like you need to create a save first and then you should be able to start the server.

**Comment by knoxfighter** [comment]
We should not start the server, when selected save / no latest save is available.

**Comment by mroote** [comment]
Agreed it's not clear that you need to create the save file first.

**Comment by mroote** [comment]
Fixed in #242 an error will be displayed if the server is started without a savefile created.
