### ISSUE TITLE
Could not retrieve config.ini

### ISSUE THREAD

**Issue by peeves91** [OpenFactorioServerManager/factorio-server-manager#234]
so i'm trying to get this running, but i must be doing something wrong here.  it starts fine, and i do the --dir <point to factorio directory in steam>, and when i click on "Game Settings", this is the console output up until that point:

```
2021/01/23 13:47:43 Loaded Factorio settings from C:\Program Files (x86)\Steam\steamapps\common\Factorio\config\server-settings.json
2021/01/23 13:47:43 Created/Updated user: admin
2021/01/23 13:47:43 Starting server on: 0.0.0.0:80
2021/01/23 13:47:51 Loading config file: C:\Program Files (x86)\Steam\steamapps\common\Factorio\config\config.ini
2021/01/23 13:47:51 Error loading config.ini file: open C:\Program Files (x86)\Steam\steamapps\common\Factorio\config\config.ini: The system cannot find the file specified.
2021/01/23 13:47:51 Could not retrieve config.ini: open C:\Program Files (x86)\Steam\steamapps\common\Factorio\config\config.ini: The system cannot find the file specified.
```

i've tried pointing --config at the config file to the config.ini in the appdata directory, but that doesn't seem to help anything. 
 any clue if i'm doing something wrong in the startup or configuration?

(i'll provide any information or try any suggestions)

**Comment by knoxfighter** [comment]
You run the docker image, on Windows or Linux (if yes, which distribution)?

**Comment by peeves91** [comment]
there isn't a config.ini file in that location.  there is one in the appdata/roaming/factorio/config folder, but pointing to that one doesn't work.

guess i'll try downloading the server install from the site and using the experimental that way.

**Comment by jannaahs** [comment]
Hi @peeves91 do you have any update on this?

**Comment by Lezhek** [comment]
> Hi [@peeves91](https://github.com/peeves91) do you have any update on this?

I did encounter the same issue, launching the world and copying config.ini from AppData to Factorio root folder fixed the issue.
I belive the programm should look into \AppData\Roaming\Factorio\config not Steam\steamapps\common\Factorio\config
