### ISSUE TITLE
Mod page: enablement issues

### ISSUE THREAD

**Issue by samgray96** [OpenFactorioServerManager/factorio-server-manager#235]
Issue with the enablement toggle, despite a mod just being installed it will stay disabled and report that it's not installed if you try to enable it as per the log output below:

```factorio-server-manager1   | 2021/01/24 09:29:08 Error in toggling mod in simple list: mod is not installed```

**Comment by knoxfighter** [comment]
When this happens, with which mod and which version and is it similar to #236, that factorio doesn't decide to load, cause dependencies are not installed?

**Comment by samgray96** [comment]
The one I was using at the time was FNEI, but I've had it with other mods with no required dependencies, it's on the mod page, before the server is even running - I didn't happen to grab a screenshot of the mod page at the time but the error that appears in the log (above) appears in the red box down the bottom right and you are prevented from toggling the mod toggle, despite it actually showing as enabled in the JSON even

**Comment by knoxfighter** [comment]
This was caused when changing mods while the server is still running. The mods page is deactivated now in such a case.
Fixed in 0.10.0
