### ISSUE TITLE
Cannot open save file

### ISSUE THREAD

**Issue by Pwnographic** [OpenFactorioServerManager/factorio-server-manager#245]
Hey, Im trying to load mods from a save. I can launch the save just fine, its the right map. But when I tried to get mods from the save it says the save does not exist. And its very difficult to see exactly where the installation is in the files.
http://prntscr.com/xrtgpy
Is there an easier way to install this with docker to find the file directory easier? It just seems like the save isnt saving to the server and I have no idea where its located even though the manager starts the file fine..

**Comment by knoxfighter** [comment]
Is your save listed in the "Saves" page?

**Comment by Pwnographic** [comment]
Yes

**Comment by Pwnographic** [comment]
This is the log:

/opt/fsm/mod_packs
2021/01/28 21:11:59 no ModPackDir found ... creating one ...
2021/01/28 21:11:59 Server settings at /opt/factorio/config/server-settings.json not found, copying example server settings.
2021/01/28 21:11:59 Loaded Factorio settings from /opt/factorio/config/server-settings.json
2021/01/28 21:11:59 Created/Updated user: admin
2021/01/28 21:11:59 Starting server on: 0.0.0.0:80
2021/01/28 21:12:00 Unauthenticated request GET 51.222.11.151 /mods
2021/01/28 21:12:00 Unauthenticated request GET 51.222.11.151 /api/user/status
2021/01/28 21:12:00 Unauthenticated request GET 51.222.11.151 /ws
2021/01/28 21:12:03 Logging in user: admin
2021/01/28 21:12:03 User: admin, logged in successfully
2021/01/28 21:12:09 Uploading save file
2021/01/28 21:13:15 no mod-list.json found ... create new one ...
2021/01/28 21:13:37 cannot open save level file: file not found
2021/01/28 21:13:37 http: superfluous response.WriteHeader call from github.com/mroote/factorio-server-manager/api.LoadModsFromSaveHandler (mods_handler.go:324)

**Comment by Pwnographic** [comment]
2021/01/28 21:13:37 cannot open save level file: file not found
2021/01/28 21:13:37 http: superfluous response.WriteHeader call from github.com/mroote/factorio-server-manager/api.LoadModsFromSaveHandler (mods_handler.go:324)

**Comment by Pwnographic** [comment]
http://prntscr.com/xrwd67

**Comment by Pwnographic** [comment]
Oh, wierd, I tried a different save with different mods and it worked...

**Comment by knoxfighter** [comment]
Then send me the save, which doesn't work pls :)
I will have a look later.

**Comment by Pwnographic** [comment]
https://toffeeshare.com/?a82839ee1a6hlV

**Comment by Pwnographic** [comment]
Also, how would I go about launching multiple servers? I assume creating a new container?

**Comment by knoxfighter** [comment]
yes, run multiple containers and expose the ports onto a different host port.

**Comment by knoxfighter** [comment]
I only get the message "Unable to establish connection" on that link :frowning:

**Comment by Pwnographic** [comment]
https://gofile.io/d/yLMLfv

**Comment by knoxfighter** [comment]
I cannot launch a game with that save. It is an invalid save, cause it contains no `level.dat`.
The factorio server is also not starting it: `0.835 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "level.dat not found."`

For what factorio version is that save and how did you created it?

**Comment by Pwnographic** [comment]
That is...bizarre. I created it in 1.1, I want to say in 1.1.19 but it could have been a version between 1.1.12-1.1.18. I didn't manipulate the save at all so I'm not sure how that could have happened haha. That would certainly explain why its not working with that save. I guess we can just chalk this up to a isolated issue with one of the factorio beta versions, I don't know.

**Comment by knoxfighter** [comment]
When i'm correct, that was a bug in a single beta 1.1 version. So yes, this should not be an issue with any new/updated version of factorio. Also factorio 1.1 has a stable release now :)

If that ever happens again, just reopen this issue or create a new one.
