### ISSUE TITLE
Same as #245

### ISSUE THREAD

**Issue by Pwnographic** [OpenFactorioServerManager/factorio-server-manager#253]
Was unable to reopen the issue, here is another save file that I just created and uploaded that gives the error but definitely does have level.dat's in it https://gofile.io/d/QwO9iU 
edit: Ive actually tried several different saves with various modpacks and names now and none have worked. The only one I could get working was from a modded save from 1.1.13, it loaded the mods fine. Seems like all of the ones from 1.1.19 do not work
edit: tried to revert back to an older 1.1 which only 1.1.14 was an option. Tried to make a save with that version and upload it but it also didnt work. Something interesting though: The game save from 1.1.14 was only 1MB. All of the game saves from 1.1.19 are >9MB, even though these are all saves with no time in them, not sure why. Although the save I mentioned earlier from 1.1.13 that did work, had a few days of playtime on it. Maybe thats the disconnect, I have no clue. Here is a link to the game save that does seem to work from 1.1.13: https://gofile.io/d/CESVoN
edit: removed and repeated everything once more just to check consistency, no changes.

**Comment by knoxfighter** [comment]
# Factorio 1.1.14:
## Optimizations
- Improved save-game speed by up to 2x depending on the save file size.

**Comment by knoxfighter** [comment]
The format of the savefiles changed with 1.1.14. I think the information we want are inside `level.datmetadata`

**Comment by knoxfighter** [comment]
This should be fixed on branch `factorio1.1.14-saves`

**Comment by knoxfighter** [comment]
Fixed in 0.10.0.
