### ISSUE TITLE
[0.10.0] password is not "factorio" anymore

### ISSUE THREAD

**Issue by memyselfundich** [OpenFactorioServerManager/factorio-server-manager#257]
Hi! 

I´m the new guy, I´ve been using the ofsm to play with friends for a while now, and today I was doing maintance on my docker containers, and now I can´t log on into the ofsm web interface anymore. it was working fine before the update, but after updating to the "latest" version - I´m getting "Login failed. Username or Password wrong" on the login page. Is this a bug, or what am I doing wrong? Thanks alot for your help!

**Comment by knoxfighter** [comment]
We decided to give every user that still has the password "factorio" set to a random new one. The new passwords can be viewed in the console output.

**Comment by mroote** [comment]
Hi @memyselfundich,

Did you manage to get the password from the logs?

**Comment by knoxfighter** [comment]
I think he answered in the factorio forum: https://forums.factorio.com/viewtopic.php?p=538042#p538042

**Comment by mroote** [comment]
Nice I'll close this one then.

**Comment by memyselfundich** [comment]
yes, sorry for not following up! I got the password from the logs, and got it working again! Thanks alot for your quick help! and yes that forums post is mine :D

**Comment by mroote** [comment]
No problem glad to hear you got it working.
