### ISSUE TITLE
Credentials Docker install

### ISSUE THREAD

**Issue by Omaha2002** [OpenFactorioServerManager/factorio-server-manager#258]
Since the initial credentials have been removed from the .env file I can't login for the first time to start the server for the first time.

I tried admin/factorio but these are not working. README says:

**"Run the UI server and specify the directory of your Factorio server installation and the interface to run the HTTP server on. Edit the conf.json file with your desired credentials for authentication."** 

To me it is not clear where to put the credentials for the initial UI login.

README in the docker section says:

**An admin user is created initially using the credentials defined in the factorio-server-manager config file.

Users can be added and deleted on the settings page.**

But there is no factorio-server-manager config file if the server has not been started the first time I think.

![image](https://user-images.githubusercontent.com/3179748/108192777-f80fc600-7114-11eb-8b95-6c2287c228c2.png)

Apparently there is an admin user in sqlite.db, no idea what the password is:

 
![image](https://user-images.githubusercontent.com/3179748/108194394-dd3e5100-7116-11eb-9a56-dda6ec16af08.png)

so for now I'm stuck at:

![image](https://user-images.githubusercontent.com/3179748/108192918-21305680-7115-11eb-8e09-8f0984b23489.png)

with a valid certificate that is :-) (edit: I did not have a valid certificate, the reason i couldn't login after all)

**Comment by knoxfighter** [comment]
Hi, i missed that in the README. Those information is not correct anymore. The first time the manager starts (or when no db file exists), it will create an admin account with a random password. This password is printed to stdout and can be viewed in the console output of your docker container.
View it with `docker-cpompose logs` or `docker logs <containerID>`

PS: The name of the server-manager-config file is `conf.json`

**Comment by Omaha2002** [comment]
Thanks, found the password with docker-compose logs but using it with admin and the password found in the logs  still gives:

![image](https://user-images.githubusercontent.com/3179748/108198256-b20a3080-711b-11eb-96ee-db5eaac46633.png)

**Comment by knoxfighter** [comment]
Running it without SSL/TLS requires you to define "secure" to false in the conf.json:
https://github.com/OpenFactorioServerManager/factorio-server-manager/issues/247#issuecomment-777104057

**Comment by Omaha2002** [comment]
Indeed in the end it was a SSL/TLS error, after fixing that I got a:

![image](https://user-images.githubusercontent.com/3179748/108238808-99187400-7149-11eb-9781-c6757203522a.png)

and using the created password I could login:

![image](https://user-images.githubusercontent.com/3179748/108238933-b3525200-7149-11eb-89cd-252c9e174315.png)

Thank you for the directions and thank you for a nice way to manage factorio servers :-)
