### ISSUE TITLE
Develop server not starting/no save file possible

### ISSUE THREAD

**Issue by Omaha2002** [OpenFactorioServerManager/factorio-server-manager#264]
When using the docker develop version it is not possible to create the first save file.

It is possible to upload a save file but selecting it results in server exiting with a: 

![image](https://user-images.githubusercontent.com/3179748/110241424-f2a5de80-7f50-11eb-88b7-d1300b474181.png)

**Comment by knoxfighter** [comment]
First mentioned: https://github.com/OpenFactorioServerManager/factorio-server-manager/issues/261#issuecomment-788788461

**Comment by Omaha2002** [comment]
I realise I mentioned it in #261 but also that I was hijacking another issue with the mods not working.

**Comment by mroote** [comment]
I'm not able to reproduce this. Could you send the log output with the error?

**Comment by Omaha2002** [comment]
Here it is:

2021/03/08 10:58:47 Loaded Factorio settings from /opt/factorio/config/server-settings.json
2021/03/08 10:58:47 Starting server on: 0.0.0.0:80
2021/03/08 10:58:53 Error in creating Factorio save: exit status 1
2021/03/08 10:58:53 Error creating save {test}: exit status 1
2021/03/08 10:59:00 Starting Factorio server.
2021/03/08 10:59:00 Starting Factorio server with settings: {"bindip":"0.0.0.0","savefile":"eerste keer.zip","port":34197}
2021/03/08 10:59:00 Starting server with command:  /opt/factorio/bin/x64/factorio [--bind 0.0.0.0 --port 34197 --server-settings /opt/factorio/config/
server-settings.json --rcon-port 42621 --rcon-password X*************A --server-adminlist /opt/factorio/config/server-adminlist.json --start-
server /opt/factorio/saves/eerste keer.zip]
2021/03/08 10:59:00 new state, will also send to correct room
2021/03/08 10:59:00 Factorio Server:    0.000 Error Util.cpp:83: filesystem error: cannot make canonical path: Operation not permitted [/opt/factorio/
bin/x64/../../config]
2021/03/08 10:59:00 [0.000 Error Util.cpp:83: filesystem error: cannot make canonical path: Operation not permitted [/opt/factorio/bin/x64/../../confi
g]]
2021/03/08 10:59:00 Factorio process exited with error: exit status 1
2021/03/08 10:59:00 new state, will also send to correct room
2021/03/08 10:59:00 Error starting Factorio server: exit status 1
2021/03/08 10:59:01 Did not detect running Factorio server attempt: 0
2021/03/08 10:59:02 Did not detect running Factorio server attempt: 1
2021/03/08 10:59:03 Did not detect running Factorio server attempt: 2
2021/03/08 10:59:04 Did not detect running Factorio server attempt: 3
2021/03/08 10:59:04 Error starting Factorio server: exit status 1

**Comment by Omaha2002** [comment]
Hmmm now that I have a look at the logfile, it's probably something on my end, there's no /opt/factorio.

I did a clean install, deleted everything, downloaded .env and docker-compose.yaml and a docker-compose up -d.

prob did something wrong in editting .env / docker-compose.yaml.

**Comment by mroote** [comment]
The first error looks like a permission issue trying to create the server directories. It might be an issue with the permissions of your volume that prevent the save file from being created?

**Comment by Omaha2002** [comment]
That seems to be the case, thing is I didn't change any permissions and ran the docker-compose.yaml without anything else.

Server permissions:

drwxr-xr-x 5 root   root   4096 Mar  8 11:22 ./
drwxr-xr-x 6 jeroen jeroen 4096 Feb 19 07:17 ../
-rw-r--r-- 1 root   root     78 Feb 19 07:17 .env
-rw-r--r-- 1 root   root   2199 Mar  2 08:52 docker-compose.yaml
drwxr-xr-x 6 root   root   4096 Mar  8 11:22 factorio-data/
drwxr-xr-x 2 root   root   4096 Mar  8 11:23 fsm-data/
drwxr-xr-x 2 root   root   4096 Mar  8 11:13 traefik-data/

On my other "old" server  I have the same permissions on the dirs. For testing purposes I did a chmod -R 777 * on all dirs, doesn't change anything, still the same error.

**Comment by knoxfighter** [comment]
Since our docker container is running as root, drive permissions should not be of any problem. I also not yet had the time and motivation to look into this issue, sorry.
Which factorio version do you use?

It seems like factorio has problems correctly creating the right path:
`Error Util.cpp:83: filesystem error: cannot make canonical path: Operation not permitted [/opt/factorio/
bin/x64/../../config]`

**Comment by Omaha2002** [comment]
I installed factorio:latest as a test, that one works, able to create save file and start server. But of course still has the Mods error.

**Comment by mroote** [comment]
Hmm thanks for the test seems the issue is isolated to the current develop build in that case. Could you post your docker-compose file?

**Comment by Omaha2002** [comment]
I wget this one: https://raw.githubusercontent.com/OpenFactorioServerManager/factorio-server-manager/develop/docker/docker-compose.yaml

and change factorio:latest to factorio:develop

when I do a docker ps I see it's running factorio:develop

**Comment by knoxfighter** [comment]
I can reporduce this:
```
factorio-server-manager    | 2021/03/08 15:59:46 Error in creating Factorio save: exit status 1
factorio-server-manager    | 2021/03/08 15:59:46 Error creating save {eerste keer.zip}: exit status 1
```

**Comment by knoxfighter** [comment]
This does not happen, when using an ubuntu docker image. I don't understand why, that is happening :(

**Comment by Omaha2002** [comment]
I use docker on Ubuntu

**Comment by knoxfighter** [comment]
It's about the docker image: The image is built with alpine linux.

**Comment by Omaha2002** [comment]
Stable works, develop doesn't, is it because dynamic linking?

something with bind mounts?  https://docs.docker.com/storage/bind-mounts/

**Comment by knoxfighter** [comment]
To be fair, i have absolutely no idea, what is going on there. Cause the error is not caused by the server-manager, but by the factorio-server itself. I don't find any clue, why that should not work with `muslc` anymore. I would say, we can just move the docker image to use `ubuntu` or `debian`. What do you thing @mroote ?

**Comment by mroote** [comment]
I think we went with Alpine originally just to save on image size, the latest Ubuntu container is bigger but not significantly so. ~8MB on frolvlad/alpine-glibc vs ~30MB with the latest Ubuntu. If switching the base container solves the issue I don't have a problem with that.

**Comment by knoxfighter** [comment]
It does fix it on my local machine, i will create a branch with the changes later (will play gw2 now), then you can test it by easily checking out the image from dockerhub :)

**Comment by knoxfighter** [comment]
Pushed to a new branch, please test the ubuntu docker image `ofsm/ofsm:use-ubuntu-docker`.

**Comment by Omaha2002** [comment]
Did a fresh Install of ofsm/ofsm:use-ubuntu-docker, can confirm it's working:

- login in MODS with factorio account and download mods;
- create first save file;
- start server with first save file;
- connect with factorio "client" with server, download mod and play game;
- start/stop server.

**Comment by mroote** [comment]
Thanks for helping out with testing this @Omaha2002
