### ISSUE TITLE
Invalid Password

### ISSUE THREAD

**Issue by crackruckles** [OpenFactorioServerManager/factorio-server-manager#268]
Hi,

I dont know if ive done something wrong with the setup but i cannot login to the web server, i can see the login page but when i type my username of 'admin' and the Rcon password that the first initialisation generated i cant login i just keep getting password for admin wrong.

Ive tried changing the rcon in the config file and even deleting everything and starting again. 

what am i missing?

**Comment by crackruckles** [comment]
After a bunch of messing around i finally got it to work, im not sure what i did but it works now.

**Comment by mroote** [comment]
In the startup logs it should print the randomly generated admin password on the first time it's started. The rcon password is a separate password that would be used if you want to establish a connection to the rcon console from an external source.
