### ISSUE TITLE
Mod download 403

### ISSUE THREAD

**Issue by lachesis** [OpenFactorioServerManager/factorio-server-manager#272]
```Error updating mod {ArmouredBiters}: Statuscode not 200: 403```
```
2021/03/27 16:27:29 download complete
 StatusCode: 403
 Status: 403 Forbidden
2021/03/27 16:27:29 StatusCode: 403
2021/03/27 16:27:29 updateMod ... error when downloading the new Mod: Statuscode not 200: 403
```

I get the same error trying to install a mod by name. I confirmed that my credentials are correct & I can manually download mods from the mod portal.

**Comment by lachesis** [comment]
Oh I see... I used my email address instead of username for login. That doesn't work. My bad!

**Comment by cdaringe** [comment]
uggggh thank you.

**Comment by Kegath** [comment]
> Oh I see... I used my email address instead of username for login. That doesn't work. My bad!

Thank you, this was driving me insane!
