### ISSUE TITLE
Cannot login to Mod Portal

### ISSUE THREAD

**Issue by grappas** [OpenFactorioServerManager/factorio-server-manager#282]
It says:
`Error trying to login into Factorio: {"data":{},"error":"login-too-many-attempts","message":"Too many failed login attempts. Please try again later. If you have forgotten your password, you can reset it at https://factorio.com/.","status":401}
`
Is there any way to reset it?
I gave it wrong credentials before, but even after giving correct ones it still blocking my login attempts.

**Comment by jannaahs** [comment]
Hi @grappas,

this is a message from the mod portal, which belongs to Wube. It seems like you have tried to log in too many times with the wrong credentials.
This error should disappear after a while. I tried to figure out how long you need to wait, but there is no information.
Maybe they will update the wiki in the future: https://wiki.factorio.com/Web_authentication_API

I eliminated the possibility of a bug, by testing the login.
Hopefully, you could fix the problem by waiting and my comment only documents the answer for others.

Cheers!
