### ISSUE TITLE
Cant log in with Linux version (non docker)

### ISSUE THREAD

**Issue by prox32** [OpenFactorioServerManager/factorio-server-manager#285]
Hi,

there doesnt seem to be any instructions for adding an account or changing the admin password, and the randomly generated password which I think is supposed to be displayed on the console output, well there was nothing output for an admin password?

Is it possible to add new credentials to the server config file?

**Comment by mroote** [comment]
Was this running in the docker container? Might have been some issue with permissions preventing the config file from getting set but that seems odd if you are running it with the root account.
