### ISSUE TITLE
Time is incorrect

### ISSUE THREAD

**Issue by Grimshad** [OpenFactorioServerManager/factorio-server-manager#299]
Time is not localized to the server. So all the saves show the wrong time. Don't see any timezone option in the config either.

**Comment by knoxfighter** [comment]
I guess it is always shown in UTC or servertime and nothing localized at all.
We should probably change it to show it in local usertime :)

**Comment by EphDoering** [comment]
I added a PR #314 to address this. It uses [toLocaleString ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#browser_compatibility) which has good cross-browser support. I didn't think it counted as notable so I didn't add anything to the changelog.

**Comment by mroote** [comment]
Thanks @FrederickDoering!
