### ISSUE TITLE
No saves

### ISSUE THREAD

**Issue by vinnyNC** [OpenFactorioServerManager/factorio-server-manager#300]
Where do the saves sit? I could not load any saves so I loaded a backup of the docker container and it also had no saves. Are there no physical files saved? Attached is a log, any help would be appreciated.

[factorio-server-console.log](https://github.com/OpenFactorioServerManager/factorio-server-manager/files/7621575/factorio-server-console.log)

**Comment by knoxfighter** [comment]
It is saved inside the container in `/opt/factorio/saves`.
The docker-compose files we have in this repo are exporting it via volume: `- "./factorio-data/saves:/opt/factorio/saves"`.
If you use these docker-files, saves are located in `./factorio-data/saves`
