### ISSUE TITLE
Unable to login to download mods

### ISSUE THREAD

**Issue by codefreak558** [OpenFactorioServerManager/factorio-server-manager#302]
When I try and login to try download mods for the server I get the following error `Given username or email and password do not match any account.`

**Comment by jannaahs** [comment]
Hi @codefreak558,
please check your credentials first. You can try to [login to the mod portal](https://factorio.com/login).

Last time I checked on the feature the login did work (reference #282).

**Comment by codefreak558** [comment]
Hi @jannaahs,

Thanks I tried today and it seems to be working it could've been it wanting to probigate
