### ISSUE TITLE
-dir not working?

### ISSUE THREAD

**Issue by DocterDum** [OpenFactorioServerManager/factorio-server-manager#304]
I have an existing server installed to /opt/factorio

I downloaded/unzipped fsm into /opt/fsm, and am running the executable with:
   [/opt/fsm]$  ./factorio-server-manager -dir /opt/factorio

This returns errors: 
/opt/fsm/mod_packs
2022/01/27 14:09:14 no mods dir found ... creating one ...
2022/01/27 14:09:14 no ModPackDir found ... creating one ...
2022/01/27 14:09:14 Server settings at config/server-settings.json not found, copying example server settings.
2022/01/27 14:09:14 failed to open example server settings: open data/server-settings.example.json: no such file or directory
2022/01/27 14:09:14 Error occurred during Server initialization: open data/server-settings.example.json: no such file or directory

All of these files DO exist under /opt/factorio - So it seems as though the -dir option is entirely non-functional?

I also tried:
 - Editing conf.json with "config_file", "config_directory" and "settings-file" to no avail
 - Running [/opt/factorio]$  ./../fsm/factorio-server-manager 
    - Can't find conf.json and crashes

Overall it seems that running fsm from a separate folder is entirely impossible atm...

**Comment by knoxfighter** [comment]
you need 2 `-`!
So your command results in `./factorio-server-manager --dir /opt/factorio`.

**Comment by DocterDum** [comment]
Aah, the installation page lists all arguments as a single `-` though the example there does seem to be correct, will test now

**Comment by DocterDum** [comment]
`--` has done it, thanks for the help!
