### ISSUE TITLE
Web UI: path.split is not a function

### ISSUE THREAD

**Issue by Mattie112** [OpenFactorioServerManager/factorio-server-manager#305]
Hi Guys,

I'm on the develop branch (due to RCON port). The web-ui was working yesterday but not today. I don't think I applied an update but I'm not 100% sure.

Whenever I try to go to the webinterface I get an `path.split is not a function`

![image](https://user-images.githubusercontent.com/662896/151596886-083a6dbd-84e1-49b3-8acf-7232c67446c7.png)

If I go back from develop to the regular one (no tag) it works again. Doesn't seem to be my browser (tried some others) but I don't really get why it is not working anymore.

Are other people also having issues? The source seems to be minimized / obfuscated so I can't really trace it.

**Comment by jannaahs** [comment]
Hey @Mattie112 ,
react forms had a breaking change. This should be fixed in PR #286.
