### ISSUE TITLE
Unraid Docker server-manager only loads latest/experimental factorio version

### ISSUE THREAD

**Issue by RyleyRobinson** [OpenFactorioServerManager/factorio-server-manager#315]
there is no way to select the normal version 1.1.53 in the automatic update, 
the beta version 1.1.55 is always pulled, 
so this server does not work with Steam, the current version there is 1.1.53

please help me how can i solve the problem

**Comment by Mattie112** [comment]
Add an env var to your container. Call it FACTORIO_VERSION and give it the value 'stable'

**Comment by RyleyRobinson** [comment]
Hi @Mattie112, 
thanks for the fast answer, I tried that, unfortunately no change

I found this https://www.factorio.com/download according to this explanation I need server version 1.1.53

**Comment by RyleyRobinson** [comment]
that should be the source of the server versions, 

https://hub.docker.com/r/ofsm/ofsm/tags

unfortunately I don't see a version number there

**Comment by Mattie112** [comment]
For me adding the env var mentioned above works. I am running it in docker so if you run it differently I assume it also works in the config file?

**Comment by RyleyRobinson** [comment]
![image](https://user-images.githubusercontent.com/98637557/155890636-92192376-61ae-43ad-9040-e994c0a6d89f.png)

**Comment by RyleyRobinson** [comment]
![image](https://user-images.githubusercontent.com/98637557/155890723-65f48eb2-c554-4b57-9289-0564ea653064.png)

**Comment by Mattie112** [comment]
How did you set the environment variable?

**Comment by knoxfighter** [comment]
Depending on what your way to create the docker container is, the env variables are only changed when the container is rebuilt.
When using our docker-compose yml you should do the change, then `docker-compose down && docker-compose up -d`
The correct version of factorio is downloaded on startup of the container with the `entrypoint.sh` script.
Downloaded from: `https://www.factorio.com/get-download/${FACTORIO_VERSION}/headless/linux64`

**Comment by Mattie112** [comment]
`the env variables are only changed when the container is rebuilt.`

You can override any variables that are set during the build. Both with docker-compose or a regular "docker create/run" command.

But indeed you need to restart/recreate your container.

**Comment by RyleyRobinson** [comment]
Thank you for your replies, unfortunately they are of no help to me.
Because I don't understand them. I would be very happy if you could explain it to me in such a way that a beginner like me can do it.
Please step by step, please provide clear explanations without technical terms, what exactly do I have to do first,

**Comment by Mattie112** [comment]
First start by telling us How you run FSM? Docker? Windows? Linux? What are your settings?

You said you changed the environment var but it didn't work, show: how did you set it? Then we can confirm that is the right way.

You are not really providing enough information to properly point you in the right direction (other then what was already mentioned)

**Comment by RyleyRobinson** [comment]
> neu starten/neu erstellen.

Depending on how you create the Docker container,
==> I install the "applications" and then I can adjust or change something in the Docker settings
![image](https://user-images.githubusercontent.com/98637557/155900717-94f7d145-c43a-4f09-8943-fb9dd8d4d466.png)

**Comment by RyleyRobinson** [comment]
![image](https://user-images.githubusercontent.com/98637557/155900751-1e51bfaf-1bae-48cd-a508-ae827da81647.png)

**Comment by knoxfighter** [comment]
I guess the easiest and direct way would be if you join the discord: https://discord.gg/SB647WmSbU

**Comment by Mattie112** [comment]
OK, so you use Unraid. Great, so do I. Just add the following variable and restart.

![Screenshot_20220227-224001_Chrome](https://user-images.githubusercontent.com/662896/155901018-a03159f8-724a-4878-85a1-2bf1ef4f450d.jpg)

Edit
And for those who don't know Unraid. It's a Unix based server OS (with docker support and a web UI to manage containers)

It should work with this. But don't forget to restart the container

**Comment by Mattie112** [comment]
@RyleyRobinson did you get it to work? I have a 2nd server (mods) that got updated after restart, setting this variable fixed it again.

**Comment by RyleyRobinson** [comment]
Hello Mattie112,

Thank you very much for your great explanation and of course everyone else.

I did exactly what you said, at least I hope so
my steps:
1.) As you wrote << Just add the following variable and reboot. >> that's exactly what I did
2.) then I restarted the container, starts without errors, but in the WebUI the page remains blank

ok then I thought to myself what exactly do you mean by restart, so I pressed << force update>> and as far as I understood that then the dock was deleted and downloaded again.

My log file and my docker settings see below

![image](https://user-images.githubusercontent.com/98637557/156896793-eb231621-d557-4180-ae4c-859911124574.png)

![image](https://user-images.githubusercontent.com/98637557/156896811-809ac6aa-4bfc-462a-afd7-0b75976a2e86.png)

![image](https://user-images.githubusercontent.com/98637557/156896888-1950fade-beb4-4a2c-8061-e27eef2df423.png)

**Comment by RyleyRobinson** [comment]
Do you have an idea why the server isn't starting properly now?

I also tried removing the variable again, but unfortunately that didn't change anything, it can be started, but the page remains blank when the web UI is opened.

Should I completely delete and reinstall Docker, and if so, what is the best way to do that?

**Comment by Mattie112** [comment]
Just to confirm:

I get a new container from the app store, start it, its on the latest version, add the env variable, and restart it (done automatically) and it is on stable with no problem.
![Screenshot 2022-03-07 084623](https://user-images.githubusercontent.com/662896/156989640-cb919146-10ca-4c92-8d06-66e4ef42d9df.jpg)
![Screenshot 2022-03-07 084748](https://user-images.githubusercontent.com/662896/156989649-18307353-6457-486b-9421-d0fcc7239888.jpg)
![Screenshot 2022-03-07 084755](https://user-images.githubusercontent.com/662896/156989658-a618bad2-a35f-4918-b715-7345373d1dbb.jpg)
![Screenshot 2022-03-07 084819](https://user-images.githubusercontent.com/662896/156989677-190511c9-e4ab-4c13-9094-c43a0a59b88d.jpg)
![Screenshot 2022-03-07 084916](https://user-images.githubusercontent.com/662896/156989688-f6f29ee4-237d-4f1b-ad18-60cac7d24d04.jpg)

Reinstalling Docker should not be needed but if you want you can go to settings -> docker and then turn it off. There is also a "docker vdisk location" listed, if you remove that file and then durn docker on again everything is gone. Well everything except the stuff in /mnt/user/appdata so you might want to clear that to.

**Comment by jeanfbrito** [comment]
I had the same problem today. There is a way to select the exact version that the server runs? I don't want auto update.

**Comment by jeanfbrito** [comment]
Found it! Just add the exact version number to the variable and the image will use that version. Thanks!

I would at least use the `stable` version by default. My problem is that the server was in the experimental 1.1.56 and steam is on 1.1.53 that is the stable version. Counter intuitive to be the "beta" version the default.

**Comment by knoxfighter** [comment]
That is a different issue, but here is the answer nonetheless:
Just change the FACTORIO_VERSION to the factorio version you want. e.g. `1.1.53`

**Comment by jeanfbrito** [comment]
> That is a different issue, but here is the answer nonetheless: Just change the FACTORIO_VERSION to the factorio version you want. e.g. `1.1.53`

Thanks for the reply! My problem happened on Unraid too. That's why I found it.
