### ISSUE TITLE
Doker auto updates on experimental release

### ISSUE THREAD

**Issue by Akuno1** [OpenFactorioServerManager/factorio-server-manager#330]
Yesterday the docker did an update on the experimental release 1.1.62. Which meant my friend and I were on the wrong version of our local game. We did force Steam to do an update but I would much rather have the docker only update on stable versions. I couldn't find an option for that. I would request to either have the docker only update to stable releases or give us an option. If there is already an option, please tell me where. Thank you very much. :)

**Comment by Mattie112** [comment]
You can use an environment variable. See: https://github.com/OpenFactorioServerManager/factorio-server-manager/issues/315

**Comment by Akuno1** [comment]
Thanks this helped a lot. I will leave it on beta 1.1.65 until this version becomes stable and then I can change my server settings to only use the stable version. Because else I couldn't use my world.
