### ISSUE TITLE
Install Update mod error

### ISSUE THREAD

**Issue by ghost** [OpenFactorioServerManager/factorio-server-manager#334]
Error

Install mod tips

2022/10/30 08:49:00 StatusCode: 403
2022/10/30 08:49:00 Error downloading a mod: Statuscode not 200: 403
﻿
Update mod tips

2022/10/30 08:48:49 StatusCode: 403
2022/10/30 08:48:49 updateMod ... error when downloading the new Mod: Statuscode not 200: 403
2022/10/30 08:49:00 skipping dependency '? base >= 1.1.35' in 'flib': optional dependency or invalid format
2022/10/30 08:49:00 download complete

**Comment by Mattie112** [comment]
There is a field for your mod-portal username/password. You need to be logged in in order to download mods.

403 is a HTTP Access Denied so I think there is something wrong with your credentials.

**Comment by ghost** [comment]
There is no problem with the password account, it has been logged in, but it is impossible to install and update mods.
![8kcYC8](https://cdn.jsdelivr.net/gh/maxage/picture@main/uPic/8kcYC8.png)

**Comment by rhyser9** [comment]
@maxage I ran into this today, try logging into the mod portal from OFSM using your username/password, rather than your email/password. That resolved it for me.

**Comment by robbionline** [comment]
I get the error with username too:
```
2023/02/21 21:01:38 the mod-file for mod flib doesn't exist!
2023/02/21 21:01:38 error when deleting mod: the mod-file for mod flib doesn't exist!
2023/02/21 21:01:38 error when creating Mod: the mod-file for mod flib doesn't exist!
2023/02/21 21:01:38 Error downloading mod {flib}, error: the mod-file for mod flib doesn't exist!
```

**Comment by Mattie112** [comment]
(it doesn't help asking in multiple threads).

Try to manually download the mod then upload it to see if that fixes the issue.

**Comment by knoxfighter** [comment]
@robbionline Sounds like it is the same error as in #329
