### ISSUE TITLE
Password not visible on Docker startup

### ISSUE THREAD

**Issue by Claw22000** [OpenFactorioServerManager/factorio-server-manager#339]
If you choose to use the docker option once your up there is no info displayed showing what the default user or password is.  I tried going in to the docker and changing the password in the /opt/fsm-data/conf.json and this didn't make a difference even after restarting the container.  

This leaves you with no way to sign in.  I prefer the docker as it will be easier to update.

I really want to use this so hope its solved soon.

Might also want to update the wiki to provide instructions on what to do with the docker after its up.

**Comment by knoxfighter** [comment]
It is only printed once, when a new password is generated (when the container is created or you have deleted the sqlite.db file). Docker is printing the log, when you are attached. If you have missed the output, or want to show it again, use `docker logs` or `docker compose logs` to view previous output.

See docker documentation for further info: https://docs.docker.com/config/containers/logging/

The option to configure the password in the conf.json file was removed a while ago.

**Comment by Claw22000** [comment]
This worked thank you! I will share this on the factorio forums.
