### ISSUE TITLE
Game saying mods aren't there?

### ISSUE THREAD

**Issue by TheGrumpyRobo** [OpenFactorioServerManager/factorio-server-manager#344]
Hello,

I have a new install of the Factorio Server Manager, and have installed Krastorio (and dependencies) straight from my Steam install to the server. They show like they are good

![image](https://user-images.githubusercontent.com/125232571/218358687-35507354-79d1-43b4-a876-0c27ff27b280.png)

However, when I go to join my server it says that it needs to sync my mods with the server and won't let me enable Krastorio, instead syncing to just a vanilla server. 

![image](https://user-images.githubusercontent.com/125232571/218358909-4aa52fae-95bb-40aa-8b05-9b335207403e.png)

Is there a step I am missing? This is my first time trying to run a modded Factorio server, so maybe I missed a step along the way.

**Comment by robbionline** [comment]
I have the same issue. I get the following error message when I try to load the mods from save:

`Error downloading mod {flib}, error: the mod-file for mod flib doesn't exist!`

**Comment by Mattie112** [comment]
I have seen this to: it seems like FSM does not (always?) download mod dependencies correctly. So if you have mod A that requires B only A is downloaded end thus the mod is not enabled because it does not work. What I usually do is just load it in my Factorio game, then copy the entire mod folder.

I think the error from you @robbionline is different, in that case you are actually downloading a mod that somehow does not work. I think if @TheGrumpyRobo looks in the log he will see that mods cannot be activated due to missing dependencies.

**Comment by knoxfighter** [comment]
I am not sure what exactly is happening from what you described.
Where did you generate the save you currently play (on the server or on your client and then uploaded)?
The easiest way to setup mods is to do so on the client, then upload the save you want to use to the server and then use "Load mods from save" to download all needed mods to the server.

And yes, the two described errors are different and have most likely nothing to do with each other.

**Comment by TheGrumpyRobo** [comment]
I have tried both copying my mods folder from my comuputer and uploading my save and loading the mods that way. Both ways seem to have the same result. Digging through the logs, I don't see anything listed as not being able to load. I've attached the log here (IP addresses redacted) so maybe there is something in there I am missing or I am looking in thee wrong place.
[factorio-server-console.log](https://github.com/OpenFactorioServerManager/factorio-server-manager/files/10806206/factorio-server-console.log)

**Comment by knoxfighter** [comment]
ok, i know now:
Don't use the steam factorio installation. Always run the server in a separate instance and at best a headless server. Using the steam installation gives you a lot of problems (like missing mods as you noticed). You can download the game as zip from the [factorio homepage](https://www.factorio.com/download).

**Comment by TheGrumpyRobo** [comment]
That was it! I had to install the standalone version and use the .exe with the headless server (instead of the version steam installed). Everything seems to be working now.

Thanks!
