### ISSUE TITLE
How do i change factorio server version?

### ISSUE THREAD

**Issue by TheCrazyInsanity** [OpenFactorioServerManager/factorio-server-manager#353]
Sorry for asking a simple question, but i cant find this anywhere online. My server appears to be one version ahead of the steam version somehow and i am unable to connect.

**Comment by TheCrazyInsanity** [comment]
The reason it is a version ahead is because the server is running the factorio experimental version, how do i make it run the standard version?

**Comment by Mattie112** [comment]
https://github.com/OpenFactorioServerManager/factorio-server-manager/issues/315#issuecomment-1053598476
