### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by knoxfighter** [OpenFactorioServerManager/factorio-server-manager#374]
It isn't possible to create a new user, since the prefilled "role" field is requires.
![image](https://github.com/OpenFactorioServerManager/factorio-server-manager/assets/18680546/b64fa7dd-f4cc-488f-b32e-0ca7ff37eb4d)

**Comment by Mattie112** [comment]
And when I "enable" the field (by removing the disabled flag) and type something in (gets reset to 'admin'). Then I can save the user.

![image](https://github.com/OpenFactorioServerManager/factorio-server-manager/assets/662896/142461f9-9396-4c02-a5cd-4f65cdda85f8)

**Comment by matya** [comment]
it seems like the disabled field does not get posted.

**Comment by matya** [comment]
This fixed it for me https://github.com/OpenFactorioServerManager/factorio-server-manager/pull/391

**Comment by matya** [comment]
asking @knoxfighter if this contribution is OK in this form. I found this project recently and would like to start contributing in small parts to fix some bugs or get some features polished.

**Comment by knoxfighter** [comment]
Thank you for your contribution. That was a good workaround, but i built a proper version and closed your PR.
This issue is now resolved with https://github.com/OpenFactorioServerManager/factorio-server-manager/commit/07dd1b8a30af7b8c2092bdb2ce07daa2c63ca5f3
