### ISSUE TITLE
Can't find password in unraid

### ISSUE THREAD

**Issue by Culbertson1991** [OpenFactorioServerManager/factorio-server-manager#377]
I can't log in to the FSM UI. I have been googling for hours and I am so frustrated. There is no password in my logs, the logs in unraid are only showing like the last hundred or so lines. I have googled every way I possibly can to figure out where the hell the docker logs are in unraid and can't find anything.

**Comment by Culbertson1991** [comment]
Nevermind I figured it out. After literal hours of trying to figure out where the hell unraid stores docker logs, a random reddit post had the answer I needed.

**Comment by Mattie112** [comment]
Just as an aid to others (it is not Unraid specific btw):

`docker logs <container-name>` should give you all the logs

Or if you don't have any other config: remove the data volume (or just the sqlite DB) and it will generate a new password for you.

Or another option: manually open the sqlite database and update the password that is in there.

**Comment by knoxfighter** [comment]
We also have issue #315 for unraid, where a lot of things are written down.
