### ISSUE TITLE
Unraid FSM image has extra whitespace character at the end of 'FACTORIO_VERSION' environment variable

### ISSUE THREAD

**Issue by sainsley1** [OpenFactorioServerManager/factorio-server-manager#382]
The Unraid FSM image contains the environment variable 'FACTORIO_VERSION' to control which version of Factorio is installed.
However, currently the Unraid FSM image automatically installs the latest experimental version, even when this environment variable is set to 'stable' (as it is by default).  This is because the environment variable is actually created as 'FACTORIO_VERSION ', with a single whitespace character at the end.  I have verified this through removing/readding the container a few times and each time the variable is recreated the same way.  I removed the offending whitespace character and now my server downloads the correct stable version.  Please let me know if additional info is needed.

**Comment by Mattie112** [comment]
If I take a quick look at the code. And then especially the `docker/entrypoint.sh` I don´t see a space there.

https://github.com/search?q=repo%3AOpenFactorioServerManager%2Ffactorio-server-manager%20FACTORIO_VERSION&type=code

![image](https://github.com/OpenFactorioServerManager/factorio-server-manager/assets/662896/79090771-0b11-46a9-86d4-d90443cefd8c)

(assuming linux / docker) the name of an environment variable cannot contain a space:
https://www.gnu.org/software/bash/manual/html_node/Definitions.html#index-name

```
name
A word consisting solely of letters, numbers, and underscores, and beginning with a letter or underscore. Names are used as shell variable and function names. Also referred to as an identifier.
```

So exactly what place are you seeing a space?

**Comment by sainsley1** [comment]
Hi Mattie112,

Steps to reproduce:

1. Deploy FactorioServerManager container via the Unraid 'Apps' from lordfiSh's repository using all default settings
2. Edit the newly created FactorioServerManager container
3. Observe that the Environment Variable 'FACTORIO_VERSION' contains an extra space at the end, and that the Container has, by default, been installed on the latest experimental version as opposed to the latest stable version, despite the 'FACTORIO_VERSION ' environment variable being set to 'stable' by defualt
![image](https://github.com/OpenFactorioServerManager/factorio-server-manager/assets/159409788/c7744548-df2f-4b36-b463-f0365ac321cf)
![image](https://github.com/OpenFactorioServerManager/factorio-server-manager/assets/159409788/440744c4-3c63-41a5-861b-788e5092357b)
Note how you can see my cursor in the 'FACTORIO_VERSION ' section.  This is illustrating the extra whitespace which is causing the problem.
If you remove this single whitespace character and restart the server, the Factorio version will now change from Experimental latest, to Stable latest.

Please let me know if I can provide any additional information to clarify.  Sorry for my late night question written without all needed context. :)

**Comment by Mattie112** [comment]
No problem thanks for the clarification. The thing is: this is the repo for the actual implementation of the server. The Unraid template is somewhere different. So this is not really a bug for here. I would report it at https://github.com/lordfiSh/unraid-docker-images/blob/main/repo/OpenFactorioServerManager.xml instead.

**Comment by sainsley1** [comment]
Apologies, entirely correct - the Unraid template 'support' link comes here, but that's a much more appropriate place.  Thanks!!  Closing

**Comment by Mattie112** [comment]
No problem! At least you took the effort to report it :)
