### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by Neo14TheCoder** [OpenFactorioServerManager/factorio-server-manager#385]
I unfortunatly forgot my password or it changed somehow, because I swear I know the password, but apparently it's incorrect,

Where is the User and Password information stored?

**Comment by knoxfighter** [comment]
It is saved into the sqlite.db. If you delete it while fsm is not running, you will get a new password in the console output on next startup.

**Comment by Neo14TheCoder** [comment]
Thanks! Is there a way to delete the file from a webconsole? I installed fsm on a Fedora Server.

**Comment by Mattie112** [comment]
Not through the FSM webconsole. But I a assume you somehow installed FSM (ssh?) so you can delete the file via the same way?
