### ISSUE TITLE
Can't find or set password on Unraid

### ISSUE THREAD

**Issue by GasPoweredTomato** [OpenFactorioServerManager/factorio-server-manager#386]
Originally I could find the password in the logs but now I can't, even after restarting the container. 

I have been looking for sqlite.db but can't find that in the appdata either. 

I also did not see any settings to set my own webui password.

**Comment by Mattie112** [comment]
You will only see it the first time when it is generated. Are you using Unraid? Please share a screenshot of your mapped/mounted folders.

**Comment by GasPoweredTomato** [comment]
![image](https://github.com/OpenFactorioServerManager/factorio-server-manager/assets/64394824/7ac15cf0-5781-4373-8dd3-f9ba99108977)
Here you go

**Comment by Mattie112** [comment]
Oh strange, I have also a fsm-data
![image](https://github.com/OpenFactorioServerManager/factorio-server-manager/assets/662896/c59814db-00a4-4df2-9bd5-645d76556550)

Perhaps that is the location of the config file? (Or it could be my template is old and it is no longer needed). But perhaps you can try to add that folder and see what it does.

**Comment by GasPoweredTomato** [comment]
This solved it! Now I have cong.json and sqlite.db. Thank you!

**Comment by Mattie112** [comment]
A small note for people that find this later. By adding this at a later time you will get a NEW sqlite and config, so you loose any existing config.

(You can try to recover that by browsing through your `docker volumes` or by first `docker exec` into your container to grab what you need)
