### ISSUE TITLE
Default login

### ISSUE THREAD

**Issue by jelutz77** [OpenFactorioServerManager/factorio-server-manager#394]
I hacked my way into the system after I installed, but for future reference, what is the default login?

**Comment by Mattie112** [comment]
https://github.com/OpenFactorioServerManager/factorio-server-manager/blob/develop/docker/README.md#updating-credentials-adding-and-deleting-users

**Comment by jelutz77** [comment]
So... without using docker there's no way to set up users, and the admin password will always be random, and will always need to be hacked? I installed by downloading and running the executable file.

**Comment by Mattie112** [comment]
With or without Docker does not matter. The first time the server starts it will create an sqlite database (`sqlite.db`). When it does that it will generate an user and add it to the database. It will display the credentials in the console. As long as you don't delete that database file you can log in with the same credentials. But it would be easier to change the credentials :)

**Comment by jelutz77** [comment]
Unfortunately I didn’t know to look for the login on the console so I didn’t see it. Anyway hopefully this post helps someone find it.
