### ISSUE TITLE
Clarification needed on the correct port number that FSM uses. Inconsistent across platforms.

### ISSUE THREAD

**Issue by Squelch** [OpenFactorioServerManager/factorio-server-manager#407]
Whilst editing the documentation, I have become aware that the port number that FSM uses is not consistent across the installation platforms. The Docker container suggests port 80,  Linux and Windows are preconfigured to port 8080.

Port 80 is the default for web servers, and many admin panels use this port too. Port 8080 is commonly used as an alternate for many other web UI interfaces as well. If FSM is installed using the suggested or preconfigured ports, a clash may occur that prevents these ports from being used because they are already in use.

Port 80 and 8080 are fine to use if FSM is the only web interface on the host server, so to avoid possible installation problems and support requests, it might be prudent to change the suggested and preconfigured port numbers to something like 8181.

Case example: 
CasaOS is becoming a popular home cloud server and installs itself on port 80 as the main portal into the host machine. Installing the docker image of FSM with the suggested port number of 80 will clash with this landing page and fail to start FSM during installation. As a result, importing the docker image into CasaOS' app manager will fail. The resulting errors do not make it easy pinpoint the exact nature of the problem.

Moving the suggested, and preconfigured ports to any other high numbered port may be preferable.

Once this is clarified, I propose to change the documentation to reflect the new port[s], and change the suggested localhost address for the UI to a more appropriate FQDN (launching the web ui on a possibly remote headless server is pointless)

**Comment by knoxfighter** [comment]
The Port defaults to 80 whatever platform, OS you use. It will be overriden by env FSM_PORT or the --port flag. there is no code with 8080 anywhere.
Every webserver on the internet tries to listen on Port 80 and will just tell you to define a custom port if that is not possible. That is the same way it is handled in fsm at the moment and i would not change that.

The webserver itself is not able to go to a FQDN, those are only aliases for IP-Adresses, not sure what you mean there.

**Comment by Mattie112** [comment]
Yes you will always have that problem. Yes you can use a "random" port like 8562 then chances are less that some other project already uses that so you will never avoid that.

There is however a small comment you could make on port 80. On unix systems you need to be root in order to open a port on < 1024. That is why I usually use ports above that range :)

**Comment by knoxfighter** [comment]
That still changes nothing, fsm is a webserver, therefore it should listen on the default port of webservers by default. Which is Port 80 (http) or Port 443 (https). There is the option to configure the port already, so nothing to be done here?!

**Comment by Squelch** [comment]
I got into the weeds with this one from the perspective of the documentation inconsistencies, and yes, you are absolutely right @knoxfighter, Port 90 is the default, and should be.
