### ISSUE TITLE
How to set up a new Space Age server?

### ISSUE THREAD

**Issue by fmdx** [OpenFactorioServerManager/factorio-server-manager#410]
How does one start a new Space Age server with FSM?

I'm trying to set one up for a group of friends and am new to FSM. I understand there will probably be some growing pains with the new DLC.

I'm setting this up on Unraid but am not afraid of docker-compose and environment variables...

**Comment by budak7273** [comment]
Also using Unraid. I just uploaded a save file that I created in singleplayer with Space Age enabled and the container magically got the Space Age mods for me.

**Comment by knoxfighter** [comment]
You need to restart/rebuild the container once, so it can download the 2.0 release.

**Comment by jacky4566** [comment]
Confirmed. Seems to work just fine.
Restart container. Make a new single player save and upload that zip save to the server.

**Comment by fmdx** [comment]
Thanks!
