### ISSUE TITLE
I can access the server manager page, but I can't log in because the rcon password isn't displayed in the console.

### ISSUE THREAD

**Issue by BmoChop1** [OpenFactorioServerManager/factorio-server-manager#414]
<img width="1721" alt="aaa" src="https://github.com/user-attachments/assets/afc60f97-7b22-4947-9c2e-e68fd464b0b0">
The rcon password in the conf.json file in the container also does not log in.

**Comment by BmoChop1** [comment]
I used docker-compose.simple.yaml.

**Comment by knoxfighter** [comment]
You can find the used rcon password in the output logs: `docker compose logs`

**Comment by BmoChop1** [comment]
The password is not printed. The RCON value in the CONF.JSON file inside the container is always fixed even if the container is newly created or rebuilt.

**Comment by Mattie112** [comment]
It is only printed the first time. Can you try deleting the `sqlite.db` file and then starting the server again. It should be printed in the logs.

The RCON credentials are not for logging in into the web UI, that is for RCON

**Comment by knoxfighter** [comment]
The RCON password is bugged and reset every single startup. It is printed to the out log. With docker you can view the output log by using the command `docker compose logs`, there you will see the used rcon password on every startup.

PS: I deleted the image above for security reasons.

**Comment by BmoChop1** [comment]
I deleted the sql file and rebooted and it works fine, thanks for the answer.
