### ISSUE TITLE
Factorio server version not displaying correctly on the Server Status page

### ISSUE THREAD

**Issue by dirdante2** [OpenFactorioServerManager/factorio-server-manager#415]
On the Server Status page, the Factorio server version is not being displayed correctly. 
It still shows the version that was current when I first installed the server. 

I have updated the factorio server multiple times and am now on version 2.0.10 , but the page still displays version 1.1.110.0

Server starts normaly and in log files the version is correct. any ideas?

i used tar -xf factorio.tar.gz to extract the new server version into the folder
.

**Comment by ehcorn** [comment]
I'm having a similar issue, my game says version 2.0.10 but the server says 2.0.11 though the official factorio blog says that 2.0.10 is the newest version at time of writing. Is this because of the new game DLC launch?

**Comment by knoxfighter** [comment]
@ehcorn The manager shows whatever the underlying factorio version is by calling `factorio --version` and parsing the output. At the time you wrote your comment 2.0.11 was already out as experimental version. You most likely have setup the docker container to always load `latest`, which caused it to update to 2.0.11 already, even though you haven't expected it.

**Comment by dirdante2** [comment]
yes i tryed the factorio --version command and i get 

```
Version: 2.0.11 (build 79682, linux64, headless)
Version: 64
Map input version: 1.0.0-0
Map output version: 2.0.11-3
```

that is the same version i see in the log output via facorio server manager

```
0.000 2024-10-26 12:01:16; Factorio 2.0.11 (build 79682, linux64, headless, space-age)
0.000 Operating system: Linux
0.000 Program arguments: "/root/factorio/bin/x64/factorio" "--bind" "0.0.0.0" "--port" "34197" "--server-settings" "/root/factorio/config/server-settings.json" "--rcon-port" "43600" "--rcon-password" <private> "--server-adminlist" "/root/factorio/config/server-adminlist.json" "--start-server-load-latest"
0.000 Config path: /root/factorio/config/config.ini
0.000 Read data path: /root/factorio/data
0.000 Write data path: /root/factorio [7040/7963MB]
0.000 Binaries path: /root/factorio/bin
```

so i know the correct binaray is loaded

but in the controls page i see

```
Status running
IP 0.0.0.0
Port 34197
Factorio Version 1.1.110.0
Save Load Latest
```
so i think the version is parsed but the webpage displays some other variable maybe stored in another file

also if i run domain/api/server/facVersion i get
`{"base_mod_version":"1.1.110","version":"1.1.110.0"}`
and while this was correct on install. its not the correct mod data in the factorio dir

**Comment by knoxfighter** [comment]
Make sure to restart the factorio server manager after you update factorio.

**Comment by dirdante2** [comment]
yes that was the problem..... did´t tink of that......
