### ISSUE TITLE
Server stops after playing and disconnecting

### ISSUE THREAD

**Issue by Omaha2002** [OpenFactorioServerManager/factorio-server-manager#418]
With Factorio Version 2.0.14.0 Space Age I've noticed that after disconnecting from the server the server seems to stop. I have to start the server in the UI again to resume playing.

latest lines in the log doesn't mention something about stopping the server:

14535.057 Info AppManager.cpp:310: Saving to _autosave8 (blocking).
14535.157 Info AppManagerStates.cpp:2069: Saving finished
15086.874 Info ServerMultiplayerManager.cpp:1083: Disconnect notification for peer (2)
15086.874 Info ServerMultiplayerManager.cpp:971: updateTick(897104) received stateChanged peerID(2) oldState(InGame) newState(DisconnectScheduled)
15086.874 Info ServerSynchronizer.cpp:613: nextHeartbeatSequenceNumber(905141) removing peer(2).
15087.874 Info ServerMultiplayerManager.cpp:1228: Auto saving map as /opt/factorio/saves/spaceage.zip
15087.891 Info AppManager.cpp:412: Saving game as /opt/factorio/saves/spaceage.zip
15088.007 Info AppManagerStates.cpp:2069: Saving finished

**Comment by Mattie112** [comment]
Do you have a bit more log file? This does not look strange, it is a normal shutdown. Would be great if you have the log file from when it is logged that the user is quitting.

The question here is: is Factorio shutting itself down or is OFSM shutting the server down.

**Comment by Omaha2002** [comment]
It's not OFSM nor factorio, I didn't use OFSM for months and a few months back I created backupjobs in Proxmox to a backupserver and used the stop method instead of snapshot, so it's entirely normal behaviour.

Sorry for the bug report.
