### ISSUE TITLE
Cannot log into server using default user admin and generated password found in log

### ISSUE THREAD

**Issue by lever1209** [OpenFactorioServerManager/factorio-server-manager#421]
im fairly new to docker but im very familiar with linux server administration and ive already checked the database files, configs, logs, browser console, and everything says everything is fine

docker via truenas scale
ofsm/ofsm:latest
port 80 mapped to 30045 on host

**Comment by Mattie112** [comment]
Does logging in not work or do you not get a password in the log? You could try to delete the sqlite DB then restart to generate a new password.

**Comment by lever1209** [comment]
i deleted the configs volume and re tried a few times, gave up for an hour or two, then came back and tried again and it suddenly wanted to work, again, no abnormalities in the logs or anything, i wish i could have been more useful but at least its working now?

**Comment by Mattie112** [comment]
Allright, strange but good that it works!
