### ISSUE TITLE
Take-over of repository

### ISSUE THREAD

**Issue by SANCLA** [OpenFactorioServerManager/factorio-server-manager#423]
It seems this repository is not maintained for some time now.

Is the owner willing to share this repository with others like me, so it can be maintained and updated again?

**Comment by knoxfighter** [comment]
I am still interested in this project. You don't see changes in this repo, cause i decided to rewrite it completely to fix base-issues of it. Unfortunately it takes a lot longer than anticipated. For me the code in this repo is dead at the moment and will be replaced in the future.

**Comment by Mattie112** [comment]
Why not publish that WIP so others can help?

**Comment by mroote** [comment]
@SANCLA We do accept PR's but bandwidth is limited on implementing these changes. Help reviewing and testing PR's would be appreciated but currently I am not adding other people as maintainers in the repo.

**Comment by kimberlyeet** [comment]
> the code in this repo is dead at the moment and will be replaced in the future.

@knoxfighter any updates on this?
