### ISSUE TITLE
Scrollbar issue on game configuration side

### ISSUE THREAD

**Issue by OnkelDom** [OpenFactorioServerManager/factorio-server-manager#64]
There is a bug with the size of the server settings Frame:
![df187ede-a211-11e6-9bb1-d5fe63abb434](https://cloud.githubusercontent.com/assets/6128784/20003059/7c1ecc48-a284-11e6-968e-8ab8b20f2fea.png)

**Comment by Psychomantis71** [comment]
@mroote I am unable to replicate this behaviour, is this fixed?
